import { expect, test } from '@playwright/test';

test.use({ actionTimeout: 15_000 });
const solution = `import pandas as pd
from sklearn.linear_model import LinearRegression
features = ["day", "promotion"]
model = LinearRegression()
model.fit(history[features], history["demand"])
predictions = pd.Series(model.predict(future[features]), index=future.index)`;

test('a fresh final forecast requires committed stock and all reflections before producing its recap', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Open final challenge', exact: true }).click();
  const challenge = page.getByRole('region', { name: 'Final challenge', exact: true });
  await expect(challenge).toContainText('Challenge 1');
  await expect(challenge).toContainText('2026-10-26');
  await expect(challenge.getByRole('table', { name: 'Final evaluation answers' })).toHaveCount(0);
  const editor = challenge.getByLabel('Final Python', { exact: true });
  expect(await editor.inputValue()).not.toContain('model.fit');
  await challenge.getByLabel('Final features').selectOption('promotions');
  await challenge.getByLabel('Final expectation').fill('Planned promotions and trend should beat the last-day baseline.');
  await editor.fill(solution);
  const run = challenge.getByRole('button', { name: 'Run final forecast', exact: true });
  await expect(run).toBeEnabled({ timeout: 90_000 });
  await run.click();
  await expect(challenge).toContainText('Forecast validity: valid');
  await expect(challenge.getByRole('table', { name: 'Final evaluation answers' })).toHaveCount(0);
  await expect(challenge.getByLabel('Final stock for 2026-10-26')).toHaveValue('118');
  await expect(challenge).toContainText('$12.00 sale price');
  await challenge.getByRole('button', { name: 'Commit stock and submit challenge', exact: true }).click();
  const result = challenge.getByRole('article', { name: 'Challenge 1 results', exact: true });
  // Seed1: demand118..130 step2. Last train demand116, errors2..14 average8.
  // Exact stock sums868 mugs, profit868*(12-5) =6076.
  await expect(result).toContainText('Model MAE: 0.00');
  await expect(result).toContainText('Baseline MAE: 8.00');
  await expect(result).toContainText('Profit: $6,076.00');
  const finish = challenge.getByRole('button', { name: 'Complete mission', exact: true });
  await expect(finish).toBeDisabled();
  await challenge.getByLabel('Feature reasoning').fill('Day and planned promotions are available before forecasting; the closing report is not.');
  await challenge.getByLabel('Evaluation reasoning').fill('The same seven later dates give model MAE0 versus baseline8.');
  await expect(finish).toBeDisabled();
  await challenge.getByLabel('Stocking reasoning').fill('I ordered the rounded forecast:868 mugs, no lost sales or leftovers, profit6076.');
  await finish.click();
  await expect(result.getByRole('heading', { name: 'Mission complete: challenge 1', exact: true })).toBeVisible();
  await expect(result).toContainText('The same seven later dates');
  await result.getByText('Submitted final Python', { exact: true }).click();
  await expect(result).toContainText('model.fit(history[features]');
  await expect(run).toBeDisabled();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('failed and unverified high-profit runs cannot win, and revealed retries use fresh dates and answers', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Open final challenge', exact: true }).click();
  const challenge = page.getByRole('region', { name: 'Final challenge', exact: true });
  const editor = challenge.getByLabel('Final Python', { exact: true });
  const run = challenge.getByRole('button', { name: 'Run final forecast', exact: true });
  const submit = challenge.getByRole('button', { name: 'Commit stock and submit challenge', exact: true });
  await challenge.getByLabel('Final expectation').fill('I will check late features and custom predictions.');
  await editor.fill(solution.replace('["day", "promotion"]', '["closing_requested_units"]'));
  await expect(run).toBeEnabled({ timeout: 90_000 });
  await run.click();
  await expect(challenge.getByRole('alert')).toContainText('KeyError');
  await expect(submit).toBeDisabled();
  await expect(challenge.getByRole('table', { name: 'Final evaluation answers' })).toHaveCount(0);
  await editor.fill('import pandas as pd\npredictions = pd.Series([118,120,122,124,126,128,130], index=future.index)');
  await run.click();
  await expect(challenge).toContainText('Forecast validity: unverified');
  await submit.click();
  const first = challenge.getByRole('article', { name: 'Challenge 1 results', exact: true });
  await expect(first).toContainText('Profit: $6,076.00');
  await expect(first).toContainText('Model MAE: 0.00');
  for (const label of ['Feature reasoning', 'Evaluation reasoning', 'Stocking reasoning']) await challenge.getByLabel(label).fill('A filled explanation cannot make this unverified run valid.');
  await expect(challenge.getByRole('button', { name: 'Complete mission', exact: true })).toBeDisabled();
  await expect(run).toBeDisabled();
  await expect(challenge.getByRole('button', { name: 'Reset final Python' })).toBeDisabled();
  await first.getByText('Final experiment history (2 runs)', { exact: true }).click();
  await first.getByText('Run 1: failed', { exact: true }).click();
  await expect(first).toContainText('closing_requested_units');
  await challenge.getByRole('button', { name: 'Try a fresh challenge' }).click();
  await expect(challenge).toContainText('Challenge 2:');
  await expect(challenge.getByRole('table', { name: 'Final upcoming inputs' })).toContainText('2026-11-30');
  await expect(challenge.getByRole('article', { name: 'Challenge 2 results', exact: true })).toHaveCount(0);
  await expect(submit).toBeDisabled();
  await challenge.getByLabel('Final expectation').fill('Transfer the available features to the fresh sale week.');
  await editor.fill(solution);
  await expect(run).toBeEnabled({ timeout: 90_000 });
  await run.click();
  await expect(challenge.getByLabel('Final stock for 2026-11-30')).toHaveValue('113');
  await submit.click();
  const second = challenge.getByRole('article', { name: 'Challenge 2 results', exact: true });
  await expect(second).toContainText('Model MAE: 0.00');
  await expect(second).toContainText('Baseline MAE: 4.00');
  await expect(second).toContainText('Profit: $5,684.00');
  for (const label of ['Feature reasoning', 'Evaluation reasoning', 'Stocking reasoning']) await second.getByLabel(label).fill('Known inputs, MAE0 versus4 on seven later dates,812 mugs sold with no leftovers.');
  await second.getByRole('button', { name: 'Complete mission', exact: true }).click();
  await expect(second.getByRole('heading', { name: 'Mission complete: challenge 2' })).toBeVisible();
  await expect(first).toContainText('This attempt cannot complete the mission');
});

test('valid but inaccurate forecasts fail completion; changed code and invalid stock require correction', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Open final challenge', exact: true }).click();
  const challenge = page.getByRole('region', { name: 'Final challenge', exact: true });
  const editor = challenge.getByLabel('Final Python', { exact: true });
  const run = challenge.getByRole('button', { name: 'Run final forecast', exact: true });
  const submit = challenge.getByRole('button', { name: 'Commit stock and submit challenge', exact: true });
  await challenge.getByLabel('Final expectation').fill('Trend alone may miss the sale.');
  await editor.fill(solution.replace('["day", "promotion"]', '["day"]'));
  await expect(run).toBeEnabled({ timeout: 90_000 });
  await run.click();
  await expect(challenge).toContainText('Forecast validity: valid');
  await editor.fill(`${await editor.inputValue()}\n# changed`);
  await expect(submit).toBeDisabled();
  await run.click();
  await expect(submit).toBeEnabled();
  const stock = challenge.getByLabel('Final stock for 2026-10-26');
  await stock.fill('');
  await expect(submit).toBeDisabled();
  await stock.fill('1.5');
  await expect(submit).toBeDisabled();
  await stock.fill('10001');
  await expect(submit).toBeDisabled();
  await stock.fill('118');
  await submit.click();
  const first = challenge.getByRole('article', { name: 'Challenge 1 results', exact: true });
  await expect(first).toContainText('Model MAE: 11.56');
  await expect(first).toContainText('the model did not beat the baseline');
  for (const label of ['Feature reasoning', 'Evaluation reasoning', 'Stocking reasoning']) await first.getByLabel(label).fill('Trend misses the planned promotion lift; the forecast needs improvement.');
  await expect(first.getByRole('button', { name: 'Complete mission', exact: true })).toBeDisabled();
  await challenge.getByRole('button', { name: 'Try a fresh challenge' }).click();
  await challenge.getByLabel('Final expectation').fill('Another trend-only trial.');
  await expect(run).toBeEnabled({ timeout: 90_000 });
  await run.click();
  await expect(submit).toBeEnabled();
  await submit.click();
  await challenge.getByRole('button', { name: 'Try a fresh challenge' }).click();
  await challenge.getByLabel('Final expectation').fill('Both available features should explain this third fresh fixture.');
  await editor.fill(solution);
  await expect(run).toBeEnabled({ timeout: 90_000 });
  await run.click();
  await expect(challenge.getByLabel('Final stock for 2027-01-04')).toHaveValue('150');
  await submit.click();
  const third = challenge.getByRole('article', { name: 'Challenge 3 results', exact: true });
  await expect(third).toContainText('Model MAE: 0.00');
  await expect(third).toContainText('Baseline MAE: 8.00');
  await expect(third).toContainText('Profit: $7,644.00');
});

test('reset preserves interrupted source and a failed rerun cannot submit an earlier forecast', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Open final challenge', exact: true }).click();
  const challenge = page.getByRole('region', { name: 'Final challenge', exact: true });
  const editor = challenge.getByLabel('Final Python', { exact: true });
  const run = challenge.getByRole('button', { name: 'Run final forecast', exact: true });
  const submit = challenge.getByRole('button', { name: 'Commit stock and submit challenge', exact: true });
  await challenge.getByLabel('Final expectation').fill('An interrupted run must keep its source.');
  await editor.fill('while True:\n    pass');
  await expect(run).toBeEnabled({ timeout: 90_000 });
  await run.click();
  await expect(challenge.getByRole('button', { name: 'Stop final run' })).toBeVisible();
  await challenge.getByRole('button', { name: 'Reset final Python' }).click();
  await challenge.getByText('Final experiment history (1 runs)', { exact: true }).click();
  await challenge.getByText('Run 1: failed', { exact: true }).click();
  await expect(challenge).toContainText('An interrupted run must keep its source.');
  await expect(challenge).toContainText('Run interrupted by reset.');
  await expect(challenge.locator('pre').filter({ hasText: 'while True:' })).toBeVisible();
  await expect(submit).toBeDisabled();
  await editor.fill(solution);
  await expect(run).toBeEnabled({ timeout: 90_000 });
  await run.click();
  await expect(submit).toBeEnabled();
  await editor.fill('raise ValueError("final rerun failed")');
  await run.click();
  await expect(challenge.getByRole('alert')).toContainText('final rerun failed');
  await expect(submit).toBeDisabled();
  await expect(challenge.getByRole('table', { name: 'Final evaluation answers' })).toHaveCount(0);
});
