import { expect, test } from '@playwright/test';

test('the timing timeline separates availability from saved scores and actual forecast checks', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Open leakage lesson' }).click();
  const lesson = page.getByRole('region', { name: 'Investigate feature timing' });
  const timeline = lesson.getByRole('region', { name: 'Feature availability timeline' });
  await expect(timeline).toContainText('Forecast cutoff');
  await expect(timeline).toContainText('Known before forecasting');
  const late = timeline.getByRole('button', { name: 'Inspect closing_requested_units availability', exact: true });
  await late.focus();
  await late.press('Enter');
  await expect(late).toHaveAttribute('aria-pressed', 'true');
  await expect(timeline.getByRole('region', { name: 'Selected feature timing' })).toContainText('Only after the shop closes');
  await expect(timeline).toContainText('Availability guide, not a check of your edited Python');
  const editor = lesson.getByLabel('Leakage Python', { exact: true });
  const closing = await editor.inputValue();
  await lesson.getByLabel('Timing features').selectOption('known');
  const known = await editor.inputValue();
  await editor.fill(closing);
  await lesson.getByLabel('Leakage expectation').fill('A low error may still require unavailable information.');
  const run = lesson.getByRole('button', { name: 'Run timing experiment', exact: true });
  await expect(run).toBeEnabled({ timeout: 60_000 });
  await run.click();
  const first = lesson.getByRole('region', { name: 'Timing evidence for experiment 1', exact: true });
  await expect(first).toContainText('Historical MAE: 0.00 mugs/day', { timeout: 60_000 });
  await expect(first).toContainText('Upcoming execution failed');
  await expect(first).toContainText('Timing verdict: leaked');
  await expect(first).toContainText('Future accuracy: unknown');
  await editor.fill(known);
  await expect(first).toContainText('Draft changed');
  await run.click();
  const second = lesson.getByRole('region', { name: 'Timing evidence for experiment 2', exact: true });
  await expect(second).toContainText('7 upcoming predictions returned', { timeout: 60_000 });
  await expect(second).toContainText('Timing verdict: valid');
  await expect(second).toContainText('Future accuracy: unknown');
  await editor.fill(known + '\npredictions = pd.Series([70] * len(future), index=future.index)');
  await run.click();
  const custom = lesson.getByRole('region', { name: 'Timing evidence for experiment 3', exact: true });
  await expect(custom).toContainText('Historical MAE: 7.14 mugs/day', { timeout: 60_000 });
  await expect(custom).toContainText('7 upcoming predictions returned');
  await expect(custom).toContainText('Timing verdict: unverified');
  const failedCode = 'raise ValueError("Inspect the failed attempt separately")';
  await editor.fill(failedCode);
  await run.click();
  await expect(lesson.getByRole('article', { name: 'Failed timing attempt 4', exact: true })).toBeVisible({ timeout: 60_000 });
  await expect(second).toContainText('Saved experiment 2, not the current attempt');
  await expect(lesson.getByRole('region', { name: 'Timing evidence for experiment 4', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(editor).toHaveValue(failedCode);
  await expect(first).toContainText('Timing verdict: leaked');
  await expect(second).toContainText('Timing verdict: valid');
  await expect(custom).toContainText('Timing verdict: unverified');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
