import { expect, test } from '@playwright/test';

test.use({ actionTimeout: 15_000 });

test('guided practice requires inspection and real results while hints and errors remain retryable', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Start guided practice', exact: true }).click();
  const guide = page.getByRole('region', { name: 'Practice mission' });
  await expect(guide).toContainText('Step 1 of 6');
  const next = guide.getByRole('button', { name: 'Continue to next step', exact: true });
  await expect(next).toBeDisabled();
  await page.getByRole('button', { name: '2026-09-04', exact: true }).click();
  await page.getByRole('button', { name: 'Explain demand', exact: true }).click();
  await page.getByRole('tab', { name: 'Upcoming week', exact: true }).click();
  await page.getByRole('button', { name: 'I inspected the history and future inputs' }).click();
  await next.click();
  await expect(guide).toContainText('Step 2 of 6');
  const editor = page.getByLabel('Python code', { exact: true });
  const starter = await editor.inputValue();
  await expect(editor).toContainText('model.fit');
  await page.getByLabel('Your prediction').fill('A broken script should be retryable.');
  await editor.fill('raise ValueError("Try again")');
  const run = page.getByRole('button', { name: 'Run forecast', exact: true });
  await expect(run).toBeEnabled({ timeout: 60_000 });
  await guide.getByRole('button', { name: 'Return to free practice' }).click();
  await run.click();
  await expect(page.getByRole('alert')).toContainText('Try again');
  await page.getByRole('button', { name: 'Resume guided practice', exact: true }).click();
  const hint = guide.getByRole('button', { name: 'Show next hint', exact: true });
  await hint.click();
  await hint.click();
  await hint.click();
  await expect(guide).toContainText('Hints viewed: 3 of 3');
  await expect(next).toBeDisabled();
  await expect(guide).toContainText('1 of 6 steps inspected');
  await editor.fill(starter);
  await run.click();
  await expect(page.getByRole('table', { name: 'Daily forecast · latest completed run' })).toBeVisible();
  await expect(next).toBeDisabled();
  await page.getByRole('button', { name: 'I inspected forecast run 2', exact: true }).click();
  await next.click();
  await expect(guide).toContainText('Step 3 of 6');
  await expect(page.getByRole('region', { name: 'Compare with a baseline' })).toBeVisible();
  await guide.getByRole('button', { name: 'Review step 2: Forecast', exact: true }).click();
  await expect(editor).toHaveValue(starter);
  await expect(guide).toContainText('Hints viewed: 3 of 3');
  await expect(guide).toContainText('Forecast run 2');
});

test('the complete practice journey fades scaffolding and preserves inspected evidence across revisits', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Start guided practice', exact: true }).click();
  const guide = page.getByRole('region', { name: 'Practice mission' });
  const next = guide.getByRole('button', { name: 'Continue to next step', exact: true });
  await page.getByRole('button', { name: '2026-09-04', exact: true }).click();
  await page.getByRole('button', { name: 'Explain demand', exact: true }).click();
  await page.getByRole('tab', { name: 'Upcoming week', exact: true }).click();
  await page.getByRole('button', { name: 'I inspected the history and future inputs' }).click();
  await next.click();
  await page.getByRole('radio', { name: /Trend \+ promotions/ }).check();
  await page.getByLabel('Your prediction').fill('Promotions should increase upcoming demand.');
  const forecast = page.getByRole('button', { name: 'Run forecast', exact: true });
  await expect(forecast).toBeEnabled({ timeout: 60_000 });
  await forecast.click();
  await page.getByRole('button', { name: 'I inspected forecast run 1', exact: true }).click();
  await next.click();

  const evaluation = page.getByRole('region', { name: 'Compare with a baseline' });
  await evaluation.getByLabel('Evaluation features').selectOption('promotions');
  await evaluation.getByLabel('Evaluation expectation').fill('The promotion model should beat the last-day baseline.');
  const compare = evaluation.getByRole('button', { name: 'Run comparison', exact: true });
  await expect(compare).toBeEnabled({ timeout: 60_000 });
  await compare.click();
  await expect(evaluation.getByRole('article')).toContainText('Model MAE: 0.00');
  await expect(next).toBeDisabled();
  await evaluation.getByRole('button', { name: 'I inspected evaluation run 1', exact: true }).click();
  await next.click();

  const missing = page.getByRole('region', { name: 'Repair missing data' });
  const missingRun = missing.getByRole('button', { name: 'Run missing-data experiment', exact: true });
  await missing.getByLabel('Missing-data expectation').fill('Untreated missing values should fail.');
  await expect(missingRun).toBeEnabled({ timeout: 60_000 });
  await missingRun.click();
  await expect(missing.getByRole('article', { name: 'Missing-data run 1', exact: true })).toContainText('Input X contains NaN');
  await missing.getByLabel('Preparation choice').selectOption('median');
  const missingEditor = missing.getByLabel('Missing-data Python', { exact: true });
  const partialRepair = await missingEditor.inputValue();
  expect(partialRepair).not.toContain('imputer.fit_transform');
  for (let i = 0; i < 3; i++) await guide.getByRole('button', { name: 'Show next hint' }).click();
  await expect(missingEditor).toHaveValue(partialRepair);
  await expect(next).toBeDisabled();
  await missingRun.click();
  await expect(missing.getByRole('article', { name: 'Missing-data run 2', exact: true })).toContainText('NotImplementedError');
  await expect(next).toBeDisabled();
  const repaired = partialRepair.replace('raise NotImplementedError("Write the preparation block")', 'X_train = imputer.fit_transform(history[features])\nX_future = imputer.transform(future[features])');
  await missingEditor.fill(repaired);
  await missing.getByLabel('Missing-data expectation').fill('Training-only fill values should produce a usable comparison.');
  await missingRun.click();
  await expect(missing.getByRole('article', { name: 'Missing-data run 3', exact: true })).toContainText('Model MAE: 4.00');
  await missing.getByRole('button', { name: 'I inspected repaired run 3', exact: true }).click();
  await next.click();

  const timing = page.getByRole('region', { name: 'Investigate feature timing' });
  await timing.getByLabel('Leakage expectation').fill('The report looks closely related to demand.');
  const timingRun = timing.getByRole('button', { name: 'Run timing experiment', exact: true });
  await expect(timingRun).toBeEnabled({ timeout: 60_000 });
  await timingRun.click();
  await expect(timing.getByRole('article', { name: 'Timing experiment 1', exact: true })).toContainText('Validity: leaked');
  await expect(next).toBeDisabled();
  await timing.getByLabel('Timing features').selectOption('known');
  await timing.getByRole('button', { name: 'Start independent timing repair', exact: true }).click();
  const timingEditor = timing.getByLabel('Leakage Python', { exact: true });
  const partialTiming = await timingEditor.inputValue();
  expect(partialTiming).not.toContain('model.fit');
  expect(partialTiming).not.toContain('model.predict');
  await timingRun.click();
  await expect(timing.getByRole('article', { name: 'Failed timing attempt 2', exact: true })).toContainText('NotImplementedError');
  for (let i = 0; i < 3; i++) await guide.getByRole('button', { name: 'Show next hint' }).click();
  await expect(next).toBeDisabled();
  await timingEditor.fill(partialTiming.replace('raise NotImplementedError("Write the training and prediction block")', 'model = LinearRegression()\nmodel.fit(history[features], history["demand"])\npredictions = pd.Series(model.predict(future[features]), index=future.index)'));
  await timing.getByLabel('Leakage expectation').fill('Known inputs should forecast without the closing report.');
  await timingRun.click();
  await expect(timing.getByRole('article', { name: 'Timing experiment 3', exact: true })).toContainText('Validity: valid');
  await timing.getByRole('button', { name: 'I inspected valid timing experiment 3', exact: true }).click();
  await next.click();

  const stock = page.getByRole('region', { name: 'Stock the shop' });
  await stock.getByRole('button', { name: 'Plan stock from forecast run 1', exact: true }).click();
  await stock.getByRole('button', { name: 'Advance shop and reveal demand', exact: true }).click();
  await expect(guide).not.toContainText('Practice journey complete');
  await stock.getByRole('button', { name: 'I inspected stocking decision 1', exact: true }).click();
  await expect(guide).toContainText('6 of 6 steps inspected');
  await expect(guide).toContainText('Practice journey complete');
  await expect(guide).toContainText('does not award a final win');
  await guide.getByRole('button', { name: 'Review step 4: Repair', exact: true }).click();
  await expect(missingEditor).toHaveValue(repaired);
  await expect(missing.getByRole('article')).toHaveCount(3);
  await expect(guide).toContainText('Hints viewed: 3 of 3');
  await guide.getByRole('button', { name: 'Return to free practice' }).click();
  await page.getByRole('button', { name: 'Resume guided practice' }).click();
  await expect(missing.getByRole('article')).toHaveCount(3);
  await expect(guide).toContainText('Missing-data run 3');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
