import { expect, test } from '@playwright/test';

test.use({ actionTimeout: 15_000 });

test('the shop reveal replays saved outcomes without recommitting and resumes safely', async ({ page }) => {
  test.setTimeout(180_000);
  await page.goto('/');
  await page.getByLabel('Your prediction').fill('Some days need more stock than others.');
  await page.getByLabel('Python code', { exact: true }).fill('predictions = [60] * 7');
  const run = page.getByRole('button', { name: 'Run forecast', exact: true });
  await expect(run).toBeEnabled({ timeout: 60_000 });
  await run.click();
  const shop = page.getByRole('region', { name: 'Stock the shop', exact: true });
  await shop.getByRole('button', { name: 'Plan stock from forecast run 1', exact: true }).click();
  await shop.getByLabel('Stock for 2026-09-28').fill('100');
  await shop.getByLabel('Stock for 2026-09-29').fill('0');
  const replay = shop.getByRole('region', { name: 'Shop playback', exact: true });
  await expect(replay).toHaveCount(0);
  await expect(shop).toContainText('Actual demand stays hidden until you commit');
  await shop.getByRole('button', { name: 'Advance shop and reveal demand', exact: true }).click();
  await expect(replay).toBeVisible();
  await replay.getByRole('button', { name: 'Pause playback', exact: true }).click();
  await replay.getByRole('button', { name: 'View day 1: 2026-09-28', exact: true }).click();
  await expect(replay).toContainText('76 sold');
  await expect(replay).toContainText('24 leftovers cleared');
  await expect(replay).toContainText('$436.00');
  await replay.getByRole('button', { name: 'View day 2: 2026-09-29', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(replay).toContainText('78 unfilled');
  await expect(replay).toContainText('0 stocked');
  await replay.getByRole('button', { name: 'Skip to week results', exact: true }).click();
  await expect(replay).toContainText('Week complete');
  await expect(replay).toContainText('$2,536.00');
  await replay.getByRole('button', { name: 'Replay animation', exact: true }).click();
  await expect(replay).toContainText('Morning delivery');
  await expect(replay).toContainText('Week complete', { timeout: 45_000 });
  await expect(replay).toContainText('$2,536.00');
  await replay.getByRole('button', { name: 'Replay animation', exact: true }).click();
  await expect(shop.getByRole('table', { name: 'Stocking comparison', exact: true }).getByRole('row')).toHaveCount(2);
  await page.reload();
  await expect(replay).toContainText('Week complete');
  await expect(replay).toContainText('$2,536.00');
  await expect(shop.getByLabel('Stock for 2026-09-28')).toHaveValue('100');
  await expect(shop.getByRole('button', { name: 'Advance shop and reveal demand', exact: true })).toBeDisabled();
  await expect(shop.getByRole('table', { name: 'Stocking comparison', exact: true }).getByRole('row')).toHaveCount(2);
});

test('reduced motion shows static saved results, with zero and capacity orders and independently viewable revisions', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/');
  await page.getByLabel('Your prediction').fill('No stock means no fulfilled orders.');
  await page.getByLabel('Python code', { exact: true }).fill('predictions = [0] * 7');
  const run = page.getByRole('button', { name: 'Run forecast', exact: true });
  await expect(run).toBeEnabled({ timeout: 60_000 });
  await run.click();
  const shop = page.getByRole('region', { name: 'Stock the shop', exact: true });
  await shop.getByRole('button', { name: 'Plan stock from forecast run 1', exact: true }).click();
  const commit = shop.getByRole('button', { name: 'Advance shop and reveal demand', exact: true });
  await commit.click();
  const replay = shop.getByRole('region', { name: 'Shop playback', exact: true });
  await expect(replay).toContainText('Week complete');
  await expect(replay).toContainText('0 sold + 598 unfilled');
  await expect(replay.getByRole('button', { name: 'Pause playback', exact: true })).toHaveCount(0);
  await shop.getByRole('button', { name: 'Revise stock for a replay', exact: true }).click();
  await shop.getByLabel('Stock for 2026-09-28').fill('10000');
  await commit.click();
  await expect(replay).toContainText('Decision 2 · Forecast run 1');
  await expect(replay).toContainText('Revised stock · replay of already revealed demand');
  await expect(replay).toContainText('-$39,164.00');
  await replay.getByRole('button', { name: 'View day 1: 2026-09-28', exact: true }).click();
  await expect(replay).toContainText('9924 leftovers cleared');
  await replay.getByRole('button', { name: 'View day 2: 2026-09-29', exact: true }).click();
  await expect(replay).toContainText('0 stocked');
  await expect(replay).toContainText('78 unfilled');
  await shop.getByLabel('View saved decision').selectOption('1');
  await expect(replay).toContainText('Decision 1 · Forecast run 1');
  await expect(replay).toContainText('0 sold + 598 unfilled');
  await expect(shop.getByRole('table', { name: 'Stocking comparison', exact: true }).getByRole('row')).toHaveCount(3);
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test('leaving the shop pauses playback until the learner resumes it', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('Your prediction').fill('Watch a saved week.');
  await page.getByLabel('Python code', { exact: true }).fill('predictions = [0] * 7');
  await page.getByRole('button', { name: 'Run forecast', exact: true }).click({ timeout: 60_000 });
  await page.getByRole('button', { name: 'Plan stock from forecast run 1', exact: true }).click();
  await page.getByRole('button', { name: 'Advance shop and reveal demand', exact: true }).click();
  const replay = page.getByRole('region', { name: 'Shop playback', exact: true });
  await replay.getByRole('button', { name: 'Pause playback', exact: true }).click();
  await replay.getByRole('button', { name: 'Next stage', exact: true }).click();
  await replay.getByRole('button', { name: 'Play playback', exact: true }).click();
  await page.getByRole('button', { name: 'Open final challenge', exact: true }).click();
  await expect(replay).toBeHidden();
  // Longer than one playback stage: hidden activity must not advance its timer.
  await page.waitForTimeout(2100);
  await page.getByRole('button', { name: 'Back to practice', exact: true }).click();
  await expect(replay.getByRole('button', { name: 'Play playback', exact: true })).toBeVisible();
  await expect(replay).toContainText('Customers place orders · Paused');
});
